### ISSUE TITLE
isDirty()

### ISSUE THREAD

**Issue by kmusham** [4Q-s-r-o/signature#1]

**Comment by kmusham** [comment]
Can you expose new API to see if the canvas is dirty or not for the validation purpose. Our requirement is not to allow an empty signature. 
 _signatureCanvas.exportBytes() is always returning non empty object.
Thanks

**Comment by ethael** [comment]
hello. sorry for late response. we will implement this feature soon. hopefully this week.

**Comment by MartinHlavna** [comment]
Released as 1.1.0

You can use new properties on ```Signature``` class - ```isEmpty``` or ```isNotEmpty``` as more appropriate in your use case.
