### ISSUE TITLE
Black area in horizontal screenmode

### ISSUE THREAD

**Issue by ea-jobvalley** [4Q-s-r-o/signature#102]
Hello,
I'm implementing a signing feature in Flutter using this nice plugin.
Unfortunately I have an issue with a mysterious black area on the screen which only appears in horizontal screen mode.
I attached a screenshot of it.

<img width="1183" alt="Screenshot 2024-02-06 at 11 51 29" src="https://github.com/4Q-s-r-o/signature/assets/59683467/83934caa-565d-44f4-ab9f-210315e09c10">

The code of the widgets build method:
```
Widget build(BuildContext context) {
    final SignatureController signatureController = SignatureController(
      penStrokeWidth: 5,
      penColor: Colors.black,
      exportBackgroundColor: Colors.white,
    );
    final signatureCanvas = Signature(
      controller: signatureController,
      backgroundColor: Colors.debugRed,
    );

    return Scaffold(
      backgroundColor: Colors.white,
      body: Expanded(
        child: signatureCanvas,
      ),
    );
  }
```

The issue appears on both Android and iOS (devices and simulators).

**EDIT**: I just replaced "signatureCanvas" with a Container() and the problem still occurs. So I guess it has nothing to do with the plugin.

**Comment by MartinHlavna** [comment]
I have been unable to reproduce this, so it indeed looks like related to something else rather than plugin.
