### ISSUE TITLE
Wrapping the signature widget in padding draws out of right boundry

### ISSUE THREAD

**Issue by JustMax7CB** [4Q-s-r-o/signature#106]
I've started to learn and try this package in order to implement signature pad into my app
and after wrapping the Signature widget with horizontal padding, I've noticed that the if you start the signature from inside the signature container, you can get out of the container bounds on the right side

![rsz_screenshot_20240507_111013 1](https://github.com/4Q-s-r-o/signature/assets/83203304/49f58e25-449c-45bc-ad59-bdaa09972942)

**Comment by MartinHlavna** [comment]
Fixed in in ```5.5.0```
