### ISSUE TITLE
How to stop painting?

### ISSUE THREAD

**Issue by boucoding** [4Q-s-r-o/signature#25]
Hi,

I have used this plugin and it really helped me thank you for this work.

but I have a question which is how to stop listening to the signature widget for any painting.

I mean it will be unpaintable.

Thank you,

**Comment by ethael** [comment]
such feature is not supported by plugin itself
as a workaround, you can wrap signature widget to GestureDetector, that would prevent signature plugin from detecting touches

**Comment by prooshani** [comment]
> such feature is not supported by plugin itself
> as a workaround, you can wrap signature widget to GestureDetector, that would prevent signature plugin from detecting touches

Hi,
I had the same issue but GestureDetector was not the correct answer for me!
I have wrapped the signature pad with `IgnorePointer()` and this way easily disabled the signature from being painted when I don't want to.

 I think it may be a good feature for this package to define a boolean like `Enabled` to easily enable/disable the signature canvas from being painted or not.

Hope it helps.
