### ISSUE TITLE
Transparent background image

### ISSUE THREAD

**Issue by PandaGeek1024** [4Q-s-r-o/signature#32]
Is there a way to export a signature image with transparent background? Thanks

**Comment by patriksharma** [comment]
@PandaGeek1024  it worked for me, Do like this when you declare controller
```
final SignatureController _controller = SignatureController(
    penStrokeWidth: 5,
    penColor: Colors.red,
    exportBackgroundColor: Colors.white,
  );
```

**Comment by PandaGeek1024** [comment]
@patriksharma but the background is white? I want transparent background

**Comment by ahuruConnect** [comment]
exportBackgroundColor: Colors.transparent does the trick for me.
