### ISSUE TITLE
Export Signature to PDF

### ISSUE THREAD

**Issue by mame306** [4Q-s-r-o/signature#38]
Hi,

I want to export the signature to a pdf file. Is it possible to do that? And how could I implement it?

Thanks for helping me

**Comment by bdlukaa** [comment]
You can do this just by saving a file with the extension `.pdf`.

See [this stackoverflow answer](https://stackoverflow.com/a/63461865/11622876)

**Comment by MartinHlavna** [comment]
Hi,

1. ```SignatureController``` allows you to export signature as pdf image by calling ```toPngBytes()``` 
2.  If you want to save signature to pdf file you have to create it. [pdf](https://pub.dev/packages/pdf) package is great way to implement it. 

Quick idea (i have not tested it, there may be errors, but it should point you to right direction): 

``` dart
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
//...

var pngBytes = signatureController.toPngBytes();
final pdf = pw.Document();
final image = pw.MemoryImage(
  pngBytes,
);

pdf.addPage(pw.Page(build: (pw.Context context) {
  return pw.Center(
    child: pw.Image(image),
  ); // Center
})); // Page

// On Flutter, use the [path_provider](https://pub.dev/packages/path_provider) library:
final output = await getTemporaryDirectory();
final file = File("${output.path}/example.pdf");
await file.writeAsBytes(await pdf.save());

```
