### ISSUE TITLE
Pixellated Signatures on Flutter Web

### ISSUE THREAD

**Issue by abhisunkewar** [4Q-s-r-o/signature#43]
![signature](https://user-images.githubusercontent.com/30751203/135074158-abc26aff-320a-4740-b811-32828824e97a.jpeg)

**Comment by MartinHlavna** [comment]
Hi,
can you please provide more context? :) 

1. This is image is Signature canvas  or exported image?
2. How are you creating Signature widget and SignatureController, what are your pen settings, etc.
3. If this is exported image how are you displaying it? Please note that toPngBytes will export data without bounding box.

**Comment by MartinHlavna** [comment]
Also please see  #30

**Comment by MartinHlavna** [comment]
Closing because of no response.
