### ISSUE TITLE
SIGNATURE NOT WORKING

### ISSUE THREAD

**Issue by ClicknetTelecom** [4Q-s-r-o/signature#45]
[signature-teste] flutter pub get
Running "flutter pub get" in signature-teste...                 
Error on line 30, column 3 of pubspec.yaml: **_A package may not list itself as a dependency._**
   ╷
30 │   signature: ^4.1.1
   │   ^^^^^^^^^
   ╵
pub get failed (65;    ╵)
exit code 65

**Comment by MartinHlavna** [comment]
Can you share your pubspec.yaml? Example works fine. From the error message it looks like your project have the same name as dependency.

**Comment by MartinHlavna** [comment]
Closing because of no response.
