### ISSUE TITLE
Bug report: Incorrect use of ParentDataWidget

### ISSUE THREAD

**Issue by h7x4** [4Q-s-r-o/signature#49]
Consider the following example app:

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:signature/signature.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final SignatureController controller = SignatureController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Signature Demo',
      home: Scaffold(
        appBar: AppBar(),
        body: Stack(
          children: [
            Signature(
              controller: controller,
              backgroundColor: Colors.black12,
            ),
            IconButton(
              icon: Icon(Icons.delete),
              onPressed: () => controller.clear(),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

When drawing, the console keeps spitting out this error message:

```command
Another exception was thrown: Incorrect use of ParentDataWidget.
```

After looking a little bit around, I found that the causing line was the last part of the build function of `SignatureState`:

```dart
    if (widget.width != null || widget.height != null) {
      //IF DOUNDARIES ARE DEFINED, USE LIMITED BOX
      return Center(
        child: LimitedBox(
          maxWidth: maxWidth,
          maxHeight: maxHeight,
          child: signatureCanvas,
        ),
      );
    } else {
      //IF NO BOUNDARIES ARE DEFINED, USE EXPANDED
      return Expanded(child: signatureCanvas);
    }
```

Wrapping the canvas inside an `Expanded` widget only makes sense if the canvas is a child of `Column`, `Row` or `Flex`. See [StackOverflow](https://stackoverflow.com/questions/54905388/incorrect-use-of-parent-data-widget-expanded-widgets-must-be-placed-inside-flex).

Although `Expanded` is needed when wrapped inside either of those three widgets, I think it would be better to let the user decide if the canvas should be expanded or not.

**Comment by MartinHlavna** [comment]
Released in 5.0.0
