### ISSUE TITLE
Drawing should not scroll a container

### ISSUE THREAD

**Issue by sma** [4Q-s-r-o/signature#5]
If the `Signature` widget is part of a scrolling container, drawing gestures cause unwanted scrolling. My expectation is that drawing inside the widget will work just fine and the container doesn't scroll.

[Attached](https://github.com/4Q-s-r-o/signature/files/2901332/main.dart.zip) is a simple example that demonstrates the problem. If you try to draw something inside the amber signature widget, the `ListView` scrolls and subscribing is nearly impossible.

Perhaps using a `GestureDetector` instead of a `Listener` widget would help?

**Comment by MartinHlavna** [comment]
Hi, thanks for the report.

**Comment by danvick** [comment]
First of all awesome package @MartinHlavna.

@sma, While the authors work on the issue, I'd suggest wrapping the widget inside a `GestureDetector` with an empty `onVerticalDragUpdate` as suggested [here](https://stackoverflow.com/a/54939269/2949916) on StackOverflow.

Worked for me.
