### ISSUE TITLE
How cann i show signature from url?

### ISSUE THREAD

**Issue by MohsinIkram777** [4Q-s-r-o/signature#54]
I'm saving signature to server and server gives me an url. So kindly can you tell how can i show signature from url?

**Comment by MartinHlavna** [comment]
Hello,

I assume you are saving exported PNG on server? I would recommend ```cached_network_image``` package for this. 

If you have exported points on the server (as an json for example) you would have to download them and supply into ```SignatureController```

**Comment by FidaMOhsin** [comment]
Dear i want  my saved signature to editable.
Like suppose when I write something on signature pad and i saved png of signature to server.
Server returns me URL of the saved png.
So now i want to write on my pervious signature, means update this.
I hope now you will get the point.
I want just we can load signature from url in signature pad.
Kindly response
