### ISSUE TITLE
Can I set the background to an image?

### ISSUE THREAD

**Issue by SittiphanSittisak** [4Q-s-r-o/signature#55]
My work needs a signature on the space like the image below.
If can show this background with an image, the user will sign with ease.
(My work needs to print this image with signature.)

![image](https://user-images.githubusercontent.com/59549741/159908043-09d50eee-aed4-4a96-858f-b77d7b9500b8.png)

**Comment by MartinHlavna** [comment]
Hi,
do you want to set background for the Signature widget, or do you want to draw exported png on top of another image?

**Comment by SittiphanSittisak** [comment]
Hi, thank you for your response. My project doesn't need this now.
