### ISSUE TITLE
toImage() returns defineable size image?

### ISSUE THREAD

**Issue by rivella50** [4Q-s-r-o/signature#56]
Hi there,
at the moment controller.toImage() and .toPngBytes() return various size images, depending on the painted dots area.
Since the backend i have to upload signature images expects fixed size images i was wondering if it wouldn't be possible to let callers of those 2 methods define optional width and height parameters which (if defined) would be used as the size of the returned image, where the signature then is centered.
If the width and/or height are smaller than the signature those values would be used.

Or how could i reach this by myself after receiving a ui.Image from controller.toImage() ?

**Comment by MartinHlavna** [comment]
Hi,

how should it behave? By adding transparent space, or by upscaling the signature?

**Comment by rivella50** [comment]
Hi Martin,
i would suggest adding transparent space, or if a background color is passed (as an additional parameter?) then use that color.

**Comment by MartinHlavna** [comment]
Published in ```5.2.0```

**Comment by rivella50** [comment]
Thanks a lot. I will test it asap.
