### ISSUE TITLE
Adding exportPenColor

### ISSUE THREAD

**Issue by saguado69** [4Q-s-r-o/signature#57]
Please consider that would be nice to have the exportPenColor property. For black theming ideal penColor will probably be white, while exporting penColor should be black or darker color.

Thanks in advance,

S.

**Comment by MartinHlavna** [comment]
Hi,
we will analyze the possibilities.

**Comment by MartinHlavna** [comment]
Released in ```5.0.1```

**Comment by saguado69** [comment]
Thanks!! works fine.
