### ISSUE TITLE
Feature Request: onChanged callback.

### ISSUE THREAD

**Issue by danvick** [4Q-s-r-o/signature#6]
Good work on this useful plugin.

Is there possibility of adding an `onChanged(updatedData)` callback that will notify when user interaction has stopped sending back the byte data for users to react to?

**Comment by ethael** [comment]
thanks for the input. we do not plan this feature as we do not currently need it for our projects, but we may do it in the future. feel free to create a PR for it if you are interested.

**Comment by MartinHlavna** [comment]
PR #7 solves this.

**Comment by MartinHlavna** [comment]
PR #7 has been merged. Will be released soon.
