### ISSUE TITLE
covert base64 string and pass the predefined signature to it's controller, is it possible?

### ISSUE THREAD

**Issue by ankitkrmishra123** [4Q-s-r-o/signature#67]
I have a api respose of signature in base64 String so how can I covert base64 string and pass the predefined signature to it's controller, is it possible

**Comment by ankitkrmishra123** [comment]
pls answer

**Comment by wahabsohail** [comment]
Hi, @ankitkrmishra123 did you find any solution?

**Comment by hammad-asghar** [comment]
final signatureImage = await _signatureController.toPngBytes();
final signatureEncoded = base64.encode(signatureImage!);
//save to file or Db

//show saved signatures
Image.memory(base64Decode(signatureEncoded!))

**Comment by ethael** [comment]
closing. we don't provide support implementation through tickets
