### ISSUE TITLE
Does this package support flutter on web?

### ISSUE THREAD

**Issue by KonAtPropertyMe** [4Q-s-r-o/signature#75]
In pub.dev the package does not have an indicator showing that it supports flutter on the web, however, there seem to be some issues raised that indicate that perhaps it does support the web and the web folder in the package also looks like it supports it.

Does this package support web?

**Comment by MartinHlavna** [comment]
Hello,

there should be no problem using on web.

Also I can see on pub.dev that web platform is listed as supported.
