### ISSUE TITLE
Signature Overflowing

### ISSUE THREAD

**Issue by leandrogaldino** [4Q-s-r-o/signature#78]
Why is my signature overflowing at the bottom and right?

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text("SIGNATURE")),
        body: Padding(
            padding: const EdgeInsets.all(30),
            child: Signature(
              backgroundColor: const Color.fromARGB(255, 235, 212, 138),
              controller: AppController.instance.signatureController,
            )));
  }
```
![capture](https://user-images.githubusercontent.com/62770546/212569597-7f399f8f-1c52-4226-8428-6c8fb167cc20.PNG)

**Comment by rivella50** [comment]
@leandrogaldino Try this: https://github.com/4Q-s-r-o/signature/issues/58#issuecomment-1154800152

**Comment by leandrogaldino** [comment]
> @leandrogaldino Try this: [#58 (comment)](https://github.com/4Q-s-r-o/signature/issues/58#issuecomment-1154800152)

sorry, I didn't realize there was already an answer to this in the closed issues. I'm also starting to use GitHub now, I've only seen the open issues. Now I realized that there are closed ones to look at too.

With ClipRect it worked perfectly.
