### ISSUE TITLE
Export as a file

### ISSUE THREAD

**Issue by ysoofiyani** [4Q-s-r-o/signature#8]
Hey 
How I can export signature as a file ??? I need it for saving on a table.

**Comment by MartinHlavna** [comment]
Hi,
you can use call `exportBytes` method on `Signature` object  to get png encoded signature data. Then you can just [write data to file](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) using `writeAsBytes`  method on dart `File` object.

**Comment by juliandamass** [comment]
Hi @MartinHlavna , iam beginner on flutter, can help how to write the data using writeAsBytes
