### ISSUE TITLE
Invalid width setting for iOS brush

### ISSUE THREAD

**Issue by ZYaBin** [4Q-s-r-o/signature#92]
/
![42a17d70d6aabd57126be650adbb87d2](https://github.com/4Q-s-r-o/signature/assets/48663559/6971ce02-98ed-4285-be0d-a8645230fc0c)
![00943ce4427baa65a1427b1cfb4e8844](https://github.com/4Q-s-r-o/signature/assets/48663559/05f47c2b-7c18-46f8-9347-662722a8f8a9)

**Comment by gromeroortega** [comment]
how resolve this problem?
