### ISSUE TITLE
SIgnatureController doesn't return Image from flutter/material.dart

### ISSUE THREAD

**Issue by Zeroupper** [4Q-s-r-o/signature#95]
Hey,

I am using **Flutter version 3.13.5** and have encountered an issue: the _Future<ui.Image> toImage()_ function returns an Image from _dart:ui_, not from _package:flutter/material.dart_. These two Image types are different, leading to an error when attempting to assign one to the other.

```
onTap: () async {
   final image = await _controller.toImage();
   widget.onSave(image);
},
```

Error:

> The argument type 'Image? (where Image is defined in /home/$User/fvm/versions/3.13.5/bin/cache/pkg/sky_engine/lib/ui/painting.dart)' can't be assigned to the parameter type 'Image? (where Image is defined in /home/$User/fvm/versions/3.13.5/packages/flutter/lib/src/widgets/image.dart)'.

**Comment by MartinHlavna** [comment]
Hello, this is intended behavior. If you need, you can convert ui.Image (not a widget) to  material Image (widget):

There were some documentation typos (missing namespace prefix ui.) I have corrected them.

```
onTap: () async {
   final image = await _controller.toImage();
   widget.onSave(Image.memory(
  Uint8List.view(pngBytes!.buffer)
));
},
```
