### ISSUE TITLE
_controller.isEmpty() constantly listening to changes to signature pad 

### ISSUE THREAD

**Issue by rachelwong** [4Q-s-r-o/signature#97]
I am using signature v5.4.1 and I am not able to use the `_controller.isNotEmpty()` or `_controller.isEmpty()` to constantly listen for whether the signature pad has been signed or not as user signs.

I notice that `_controller.isEmpty()` `_controller.isNotEmpty()` are only updated when the app completely refreshes/reloads. 

Below is my workaround attempt, where I have to use a `ValueListenableBuilder` to listen for the value change when the user has completed drawing. I have referred to the official docs but [the official example](https://github.com/4Q-s-r-o/signature/blob/master/example/lib/home.dart) does not describe my use case. 

I realise this is not raising a bug issue (unless someone else also experiences this), but would like to reach out to the development team and the wider community for a best practices approach to using `signature`. 

Thank you kindly for reading 🙏🏼 

```
class TestSignature extends StatefulWidget {
  @override
  State<TestSignature> createState() => _TestSignatureState();
}

class _TestSignatureState extends State<TestSignature> {
  static ValueNotifier<bool> _counterNotifier = ValueNotifier<bool>(false);

  @override
  void initState() {
    super.initState();
    _counterNotifier.value = false;
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  final SignatureController _controller = SignatureController(
      penStrokeWidth: 2.0,
      penColor: AppTheme.colorBrand0,
      exportBackgroundColor: Colors.transparent,
      exportPenColor: AppTheme.colorBrand0,
      onDrawStart: () => {},
      onDrawEnd: () => {
            _counterNotifier.value = true,
          });

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
        valueListenable: _counterNotifier,
        builder: (valueContext, bool listenableValue, _) {
          return Signature(
            key: const Key('signature'),
            controller: _controller,
            height: 150,
            backgroundColor: AppTheme.colorBrand1,
          );
        });
  }
}
```

**Comment by MartinHlavna** [comment]
Hi,
I cannot test this right now, but maybe you need to call setState to rebuild widget?

**Comment by MartinHlavna** [comment]
I have tested it and it works as expected. I have updated example to show usage
