### ISSUE TITLE
toJson: Converting object to an encodable object failed: Instance of 'Point'

### ISSUE THREAD

**Issue by freddirkse** [4Q-s-r-o/signature#98]
Looking for any tips on Json serializing the points to save in a database. 

Currently attempts throw the error: Converting object to an encodable object failed: Instance of 'Point'

**Comment by DiegoLimeiradaSilva** [comment]
Good afternoon, I also need to save the Points in json, any progress?

**Comment by freddirkse** [comment]
> Good afternoon, I also need to save the Points in json, any progress?

Sadly no. Nobody seems to be paying any attention to this project, so I found a different solution and moved on.

**Comment by DiegoLimeiradaSilva** [comment]
thanks

**Comment by MartinHlavna** [comment]
Hello,
we regularly check issue, but we have limited time budget for support, so we check and clean issues only a few times a year.

To answer question, json serialization in dart is tricky. toJson method cannot work with any object. For now, you have to convert it to map manually.
